url: http://www.alexandkealie.com/
baseurl: ''

# Site settings
title: "bintangmela2020"
email: adika.bintang.s@gmail.com
description: "Bintang and Mela are getting married on August 15, 2020"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3dbbf0
  secondary: 2f90b9  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/apretz

# Build settings
markdown: kramdown
permalink: pretty